url: "https://github.com/juancho85/csv-converter/raw/master/src/main/resources/examples/m-ratings/data.csv"
headers:
- UserID
- MovieID
- Rating
- Timestamp
template: /home/juandavid/4_perso/csv-converter/src/main/resources/examples/m-ratings/template.json
output: /tmp/output